# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('domain_model', models.CharField(max_length=100)),
                ('domain_description', models.CharField(max_length=2000)),
                ('independent_eval', models.FloatField()),
                ('first', models.IntegerField()),
                ('last', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sequences',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('accession_number', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('protein_desc', models.CharField(max_length=2000)),
                ('sequence', models.CharField(max_length=5000)),
            ],
        ),
    ]
