# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170909_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='first',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='domains',
            name='last',
            field=models.IntegerField(default=0),
        ),
    ]
