# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170909_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domains',
            name='first',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='domains',
            name='last',
            field=models.CharField(max_length=15),
        ),
    ]
